export const dynasties = [
  {
    id: 1,
    name: "Hồng Bàng",
    startYear: -2879,
    endYear: -258,
    duration: 2621,
    color: "bg-amber-800",
    keyRulers: "Kinh Dương Vương, Lạc Long Quân, Hùng Vương (18 đời)",
  },
  {
    id: 2,
    name: "Thục – An Dương Vương",
    startYear: -257,
    endYear: -179,
    duration: 78,
    color: "bg-amber-700",
    keyRulers: "An Dương Vương (Thục Phán)",
  },
  {
    id: 3,
    name: "Bắc thuộc (lần 1)",
    startYear: -179,
    endYear: 40,
    duration: 219,
    color: "bg-stone-400",
    keyRulers: "Triệu Đà, Hai Bà Trưng (khởi nghĩa)",
  },
  {
    id: 4,
    name: "Trưng Nữ Vương",
    startYear: 40,
    endYear: 43,
    duration: 3,
    color: "bg-red-500",
    keyRulers: "Trưng Trắc, Trưng Nhị",
  },
  {
    id: 5,
    name: "Bắc thuộc (lần 2)",
    startYear: 43,
    endYear: 544,
    duration: 501,
    color: "bg-stone-500",
    keyRulers: "Bà Triệu (khởi nghĩa 248), Lý Bí (khởi nghĩa 541)",
  },
  {
    id: 6,
    name: "Nhà Tiền Lý",
    startYear: 544,
    endYear: 602,
    duration: 58,
    color: "bg-blue-700",
    keyRulers: "Lý Nam Đế, Triệu Việt Vương, Hậu Lý Nam Đế",
  },
  {
    id: 7,
    name: "Bắc thuộc (lần 3)",
    startYear: 602,
    endYear: 938,
    duration: 336,
    color: "bg-stone-600",
    keyRulers:
      "Mai Hắc Đế (khởi nghĩa 722), Phùng Hưng (khởi nghĩa 791), Khúc Thừa Dụ, Ngô Quyền",
  },
  {
    id: 8,
    name: "Nhà Ngô",
    startYear: 939,
    endYear: 965,
    duration: 26,
    color: "bg-teal-600",
    keyRulers: "Ngô Quyền, Dương Tam Kha, Ngô Xương Văn",
  },
  {
    id: 9,
    name: "Nhà Đinh",
    startYear: 968,
    endYear: 980,
    duration: 12,
    color: "bg-green-700",
    keyRulers: "Đinh Tiên Hoàng, Đinh Phế Đế",
  },
  {
    id: 10,
    name: "Nhà Tiền Lê",
    startYear: 980,
    endYear: 1009,
    duration: 29,
    color: "bg-emerald-600",
    keyRulers: "Lê Đại Hành, Lê Long Đĩnh",
  },
  {
    id: 11,
    name: "Nhà Lý",
    startYear: 1009,
    endYear: 1225,
    duration: 216,
    color: "bg-yellow-600",
    keyRulers: "Lý Công Uẩn, Lý Thường Kiệt, Lý Nhân Tông, Lý Thánh Tông",
  },
  {
    id: 12,
    name: "Nhà Trần",
    startYear: 1225,
    endYear: 1400,
    duration: 175,
    color: "bg-red-700",
    keyRulers: "Trần Thái Tông, Trần Hưng Đạo, Trần Nhân Tông, Trần Quốc Tuấn",
  },
  {
    id: 13,
    name: "Nhà Hồ",
    startYear: 1400,
    endYear: 1407,
    duration: 7,
    color: "bg-orange-700",
    keyRulers: "Hồ Quý Ly, Hồ Hán Thương",
  },
  {
    id: 14,
    name: "Bắc thuộc (lần 4)",
    startYear: 1407,
    endYear: 1427,
    duration: 20,
    color: "bg-stone-500",
    keyRulers: "Lê Lợi, Nguyễn Trãi (khởi nghĩa Lam Sơn)",
  },
  {
    id: 15,
    name: "Nhà Hậu Lê",
    startYear: 1428,
    endYear: 1789,
    duration: 361,
    color: "bg-blue-600",
    keyRulers:
      "Lê Thái Tổ, Lê Thánh Tông, Lê Kính Tông; giai đoạn này bị gián đoạn bởi nhà Mạc",
  },
  {
    id: 16,
    name: "Nhà Tây Sơn",
    startYear: 1778,
    endYear: 1802,
    duration: 24,
    color: "bg-purple-600",
    keyRulers: "Nguyễn Huệ (Quang Trung), Nguyễn Nhạc, Nguyễn Lữ",
  },
  {
    id: 17,
    name: "Nhà Nguyễn",
    startYear: 1802,
    endYear: 1945,
    duration: 143,
    color: "bg-amber-600",
    keyRulers: "Gia Long, Minh Mạng, Thiệu Trị, Tự Đức, Khải Định, Bảo Đại",
  },
];

export const getTotalDuration = () =>
  dynasties.reduce((sum, d) => sum + d.duration, 0);
