function commonsUrl(file, width = 1000) {
  return `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(file)}?width=${width}`;
}

function fallbackImage(text = "VIỆT", label = "Lịch sử") {
  const s = String(text).replace(/[<>&]/g, "");
  const l = String(label).replace(/[<>&]/g, "");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 750"><defs><linearGradient id="g" x1="0" x2="1" y1="0" y2="1"><stop stop-color="#22120d"/><stop offset=".45" stop-color="#9d2f22"/><stop offset="1" stop-color="#d8b65a"/></linearGradient><pattern id="p" width="80" height="80" patternUnits="userSpaceOnUse"><path d="M0 40H80M40 0V80" stroke="rgba(255,240,163,.18)" stroke-width="2"/></pattern></defs><rect width="1200" height="750" fill="url(#g)"/><rect width="1200" height="750" fill="url(#p)" opacity=".55"/><circle cx="950" cy="120" r="210" fill="rgba(255,240,163,.16)"/><text x="80" y="365" font-family="Georgia,serif" font-size="112" font-weight="800" fill="#fff0a3">${s}</text><text x="84" y="430" font-family="Arial,sans-serif" font-size="32" fill="rgba(255,255,255,.78)">${l}</text></svg>`;
  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`;
}

const eras = [
  {
    id: "hong-bang", period: "~2879 – 258 TCN", title: "Hồng Bàng – Văn Lang", short: "Hồng Bàng",
    person: "Vua Hùng", role: "biểu tượng khởi nguyên dựng nước",
    place: "Đền Hùng, Phú Thọ",
    mark: "Truyền thuyết Lạc Long Quân – Âu Cơ, 18 đời Hùng Vương",
    file: "Cổng đền Hùng (Phú Thọ).jpg",
    source: "https://commons.wikimedia.org/wiki/File:Cổng_đền_Hùng_(Phú_Thọ).jpg",
    seal: "雄", drop: "L", capital: "Phong Châu", figure: "Các Vua Hùng",
    milestone: "Dựng nước Văn Lang",
    quote: "Dù ai đi ngược về xuôi, nhớ ngày Giỗ Tổ mùng mười tháng ba.",
    quoteAuthor: "Ca dao",
    imageCaption: "Cổng đền Hùng — di tích Quốc gia đặc biệt Phú Thọ",
    theme: "khởi nguyên",
    summary: "Lớp huyền sử đặt nền cho ý niệm cội nguồn dân tộc, từ truyền thuyết Lạc Long Quân – Âu Cơ sinh trăm trứng, 18 đời Hùng Vương dựng nước Văn Lang, tới văn minh Đông Sơn rực rỡ với trống đồng, kỹ nghệ luyện kim và nông nghiệp lúa nước.",
    detail: "Thời kỳ Hồng Bàng là điểm khởi thủy huyền thoại của lịch sử Việt Nam. Theo Đại Việt sử ký toàn thư, Kinh Dương Vương — cháu ba đời của Viêm Đế Thần Nông — lấy con gái vua hồ Động Đình, sinh ra Lạc Long Quân. Lạc Long Quân kết duyên với nàng Âu Cơ tiên nữ, sinh ra bọc trăm trứng, nở ra trăm người con trai — tổ tiên của dân tộc Bách Việt. Năm mươi con theo mẹ lên núi, năm mươi con theo cha xuống biển, người con trưởng được tôn làm vua, lấy hiệu Hùng Vương, đặt tên nước là Văn Lang. Triều đại Hùng Vương kéo dài 18 đời, kinh đô đặt tại Phong Châu (nay thuộc tỉnh Phú Thọ). Nhà nước Văn Lang được tổ chức thành 15 bộ, đứng đầu là các Lạc tướng. Đây là thời kỳ phát triển rực rỡ của nền văn minh Đông Sơn — một trong những nền văn minh đồ đồng vĩ đại nhất Đông Nam Á. Người Việt cổ đã làm chủ kỹ thuật đúc đồng thau, chế tạo ra những chiếc trống đồng khổng lồ với hoa văn tinh xảo miêu tả cảnh sinh hoạt, săn bắn, lễ hội và tín ngưỡng phồn thực. Họ canh tác lúa nước trên những cánh đồng ven sông Hồng, biết dùng trâu bò kéo cày, sống quần tụ trong các làng bản có tổ chức xã hội chặt chẽ. Tín ngưỡng thờ cúng tổ tiên, thờ thần linh tự nhiên và tục nhuộm răng đen, ăn trầu đã hình thành từ thời kỳ này. Năm 2012, UNESCO chính thức công nhận Tín ngưỡng thờ cúng Hùng Vương là Di sản văn hóa phi vật thể đại diện của nhân loại — minh chứng cho sức sống trường tồn của dòng chảy văn hóa Hồng Bàng trong tâm thức người Việt.",
    events: [
      "Kinh Dương Vương lập nước Xích Quỷ, mở đầu huyền sử dân tộc",
      "Lạc Long Quân kết duyên Âu Cơ sinh trăm trứng — truyền thuyết nguồn cội dân tộc",
      "18 đời Hùng Vương trị vì nước Văn Lang, chia thành 15 bộ, đóng đô ở Phong Châu",
      "Phát triển rực rỡ văn minh Đông Sơn với kỹ thuật đúc đồng đỉnh cao",
      "Chế tạo trống đồng — kiệt tác văn hóa, biểu tượng quyền lực và tín ngưỡng",
      "Hình thành nền nông nghiệp lúa nước, tục ăn trầu, nhuộm răng và thờ cúng tổ tiên",
      "UNESCO công nhận Tín ngưỡng thờ cúng Hùng Vương là di sản thế giới (2012)",
    ],
  },
  {
    id: "au-lac", period: "257 – 207 TCN", title: "Âu Lạc – An Dương Vương", short: "Âu Lạc",
    person: "An Dương Vương", role: "người dựng thành Cổ Loa",
    place: "Cổ Loa, Đông Anh, Hà Nội",
    mark: "Hợp nhất Âu Việt – Lạc Việt, thành Cổ Loa, truyền thuyết nỏ thần",
    file: "An Duong Vuong Temple Co Loa Golden Turtle Magic Crossbow.jpg",
    source: "https://commons.wikimedia.org/wiki/File:An_Duong_Vuong_Temple_Co_Loa_Golden_Turtle_Magic_Crossbow.jpg",
    seal: "甌", drop: "A", capital: "Cổ Loa", figure: "An Dương Vương",
    milestone: "Xây thành Cổ Loa",
    quote: "Nỏ thần vô ý trao tay giặc, nên nỗi cơ đồ đắm biển sâu.",
    quoteAuthor: "Tản Đà",
    imageCaption: "Đền thờ An Dương Vương trong khu di tích Cổ Loa",
    theme: "thành lũy",
    summary: "An Dương Vương hợp nhất hai tộc Âu Việt và Lạc Việt lập nước Âu Lạc, dời đô xuống đồng bằng Cổ Loa, xây thành Cổ Loa hình xoắn ốc 9 vòng huyền thoại — tòa thành cổ nhất Đông Nam Á còn dấu tích.",
    detail: "Sau khi đánh bại Hùng Vương đời thứ 18, Thục Phán lên ngôi lấy hiệu An Dương Vương, hợp nhất hai bộ tộc Âu Việt (miền núi phía Bắc) và Lạc Việt (đồng bằng sông Hồng) thành nước Âu Lạc vào khoảng năm 257 TCN. Đây là bước tiến quan trọng trong quá trình mở rộng và thống nhất lãnh thổ của người Việt cổ. Nhận thấy vị trí chiến lược của vùng đồng bằng ven sông Hồng, An Dương Vương quyết định dời đô từ Phong Châu về Cổ Loa (nay thuộc huyện Đông Anh, Hà Nội). Tại đây, ông cho xây dựng thành Cổ Loa — một công trình kiến trúc quân sự độc đáo với ba vòng thành khép kín theo hình xoắn ốc, tổng chiều dài khoảng 16 km. Các nhà khảo cổ đã tìm thấy hàng vạn mũi tên đồng tại khu vực này, chứng tỏ Cổ Loa từng là một căn cứ quân sự đồ sộ. Truyền thuyết kể rằng thần Kim Quy đã giúp vua xây thành và tặng chiếc nỏ thần làm từ móng rùa vàng, có thể bắn ra hàng loạt mũi tên cùng lúc. Tuy nhiên, bị kế ly gián của Triệu Đà, Mỵ Châu đã trao bí mật nỏ thần cho Trọng Thủy. Năm 207 TCN, quân Triệu Đà tiến đánh, thành Cổ Loa thất thủ. An Dương Vương phải bỏ chạy về phương Nam, đánh dấu chương cuối của nhà nước Âu Lạc huyền thoại. Bi kịch Mỵ Châu – Trọng Thủy trở thành một trong những câu chuyện cảm động và ám ảnh nhất trong kho tàng truyền thuyết Việt Nam, để lại bài học sâu sắc về cảnh giác trước ngoại bang.",
    events: [
      "Thục Phán đánh bại Hùng Vương thứ 18, lên ngôi xưng An Dương Vương (257 TCN)",
      "Hợp nhất hai bộ tộc Âu Việt và Lạc Việt thành nhà nước Âu Lạc thống nhất",
      "Dời đô từ Phong Châu về Cổ Loa, xây dựng tòa thành xoắn ốc 9 vòng kiên cố",
      "Chế tạo nỏ Liên Châu — vũ khí bắn nhiều mũi tên cùng lúc, đỉnh cao công nghệ quân sự cổ",
      "Triệu Đà dùng kế hôn nhân Trọng Thủy – Mỵ Châu để đánh cắp bí mật nỏ thần",
      "Thành Cổ Loa thất thủ 207 TCN, kết thúc nhà nước Âu Lạc độc lập",
    ],
  },
  {
    id: "bac-thuoc", period: "207 TCN – 938", title: "Bắc thuộc & khởi nghĩa", short: "Bắc thuộc",
    person: "Hai Bà Trưng", role: "biểu tượng kháng cự",
    place: "Đền Hai Bà Trưng, Hà Nội",
    mark: "Hai Bà Trưng, Bà Triệu, Lý Bí, Mai Hắc Đế, Phùng Hưng và nhiều cuộc khởi nghĩa khác",
    file: "Hai Bà Trưng Temple, Hanoi.JPG",
    source: "https://commons.wikimedia.org/wiki/File:Hai_Bà_Trưng_Temple,_Hanoi.JPG",
    seal: "抗", drop: "H", capital: "Long Biên · Tống Bình", figure: "Hai Bà Trưng · Lý Nam Đế",
    milestone: "Khởi nghĩa liên tục",
    quote: "Tôi muốn cưỡi cơn gió mạnh, đạp luồng sóng dữ, chém cá kình ở biển Đông.",
    quoteAuthor: "Bà Triệu",
    imageCaption: "Hai Bà Trưng cưỡi voi khởi nghĩa ở Mê Linh",
    theme: "kháng cự",
    summary: "Hơn nghìn năm dưới ách các triều Hán, Đường không khuất phục được dân Việt — đây là nghìn năm lửa thử vàng, hun đúc tinh thần quật cường qua hàng loạt cuộc khởi nghĩa vang danh sử sách.",
    detail: "Thời kỳ Bắc thuộc kéo dài hơn mười thế kỷ (207 TCN – 938), là giai đoạn thử thách lớn nhất trong lịch sử dân tộc. Sau khi sáp nhập Nam Việt, nhà Triệu đặt nền cai trị phương Bắc đầu tiên lên đất Việt. Các triều đại phong kiến Trung Hoa liên tục áp đặt chính sách đồng hóa về văn hóa, ngôn ngữ và phong tục. Tuy nhiên, chính áp bức càng làm bùng lên ý chí phản kháng. Khởi nghĩa Hai Bà Trưng năm 40 SCN là cuộc nổi dậy đầu tiên giành độc lập trong ba năm, với Trưng Trắc xưng vương đóng đô ở Mê Linh. Hơn hai thế kỷ sau, Bà Triệu (Triệu Thị Trinh) mới 23 tuổi đã cưỡi voi, mặc giáp vàng, cầm gươm đánh giặc Ngô với câu nói bất hủ về khát vọng tự do. Năm 541, Lý Bí lãnh đạo khởi nghĩa đánh đuổi quân Lương, lập nước Vạn Xuân, xây điện Vạn Thọ, khẳng định nền độc lập trong gần 60 năm. Mai Thúc Loan năm 722 tập hợp hàng vạn nghĩa quân, chiếm thành Tống Bình, xưng Mai Hắc Đế và liên kết với Champa, Chân Lạp. Phùng Hưng năm 791 khởi nghĩa ở Đường Lâm, đánh chiếm thành Tống Bình, tự xưng Bố Cái Đại Vương (vua cha lớn của dân). Những thế kỷ cuối, họ Khúc do Khúc Thừa Dụ lãnh đạo đã khôn khéo giành lại quyền tự chủ (905), Dương Đình Nghệ đánh tan quân Nam Hán lần thứ nhất (931), tạo nền móng vững chắc cho trận địa cọc huyền thoại của Ngô Quyền sau này. Suốt nghìn năm, tiếng Việt, tục ăn trầu, nhuộm răng, thờ cúng tổ tiên vẫn được người dân gìn giữ như báu vật — minh chứng cho bản lĩnh văn hóa không thể đồng hóa.",
    events: [
      "Nhà Triệu sáp nhập Nam Việt 207 TCN, mở đầu hơn nghìn năm Bắc thuộc",
      "Khởi nghĩa Hai Bà Trưng (40–43): Trưng Trắc xưng vương, đóng đô Mê Linh, giành độc lập trong 3 năm",
      "Khởi nghĩa Bà Triệu (248): nữ anh hùng 23 tuổi cưỡi voi đánh giặc Ngô",
      "Lý Bí khởi nghĩa (541), lập nước Vạn Xuân, xây điện Vạn Thọ, xưng Lý Nam Đế",
      "Triệu Quang Phục kế tục kháng chiến, đánh tan quân Lương, xưng Triệu Việt Vương",
      "Mai Thúc Loan khởi nghĩa (722), xưng Mai Hắc Đế, liên minh với Champa và Chân Lạp",
      "Phùng Hưng nổi dậy (791) đánh chiếm Tống Bình, được dân phong Bố Cái Đại Vương",
      "Họ Khúc giành quyền tự chủ (905), Dương Đình Nghệ đánh tan quân Nam Hán (931)",
    ],
  },
  {
    id: "ngo", period: "939 – 965", title: "Nhà Ngô – mở nền tự chủ", short: "Ngô",
    person: "Ngô Quyền", role: "người kết thúc nghìn năm Bắc thuộc",
    place: "Đường Lâm / Bạch Đằng",
    mark: "Chiến thắng Bạch Đằng 938, xưng vương, đóng đô ở Cổ Loa",
    file: "Tượng Ngô Quyền.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Tượng_Ngô_Quyền.jpg",
    seal: "吳", drop: "C", capital: "Cổ Loa", figure: "Ngô Quyền",
    milestone: "Bạch Đằng 938",
    quote: "Đằng giang tự cổ huyết do hồng — Sông Đằng từ xưa máu vẫn đỏ.",
    quoteAuthor: "Giang Văn Minh",
    imageCaption: "Tượng Ngô Quyền — đánh tan quân Nam Hán trên sông Bạch Đằng",
    theme: "tự chủ",
    summary: "Chiến thắng Bạch Đằng năm 938 với trận địa cọc thiên tài đã chấm dứt nghìn năm Bắc thuộc. Ngô Quyền xưng vương, mở kỷ nguyên độc lập đầu tiên của dân tộc Việt.",
    detail: "Mùa đông năm 938, Ngô Quyền — con rể Dương Đình Nghệ và là tướng tài xứ Đường Lâm — dẫn quân từ Ái Châu (Thanh Hóa) ra Bắc để đối đầu đạo quân Nam Hán do Hoằng Tháo chỉ huy đang tiến vào cửa sông Bạch Đằng. Lợi dụng địa hình hiểm trở và hiểu biết sâu sắc về chế độ thủy triều, Ngô Quyền cho đóng hàng nghìn cọc gỗ lớn bịt sắt nhọn xuống lòng sông khi nước triều dâng cao. Ông sai một đội thuyền nhẹ ra khiêu chiến rồi giả vờ thua chạy, dụ đoàn thuyền địch đuổi theo vào sâu trong trận địa cọc. Khi thủy triều rút, những chiếc cọc sắt nhô lên, đâm thủng hàng loạt thuyền chiến Nam Hán. Quân của Ngô Quyền từ hai bên bờ xông ra đánh tan tác quân địch, Hoằng Tháo tử trận, vua Nam Hán phải bãi binh. Chiến thắng Bạch Đằng 938 vang dội khắp thiên hạ, chôn vùi vĩnh viễn tham vọng xâm lược phương Nam của phong kiến Trung Hoa trong nhiều thế kỷ. Ngô Quyền xưng vương, đóng đô ở Cổ Loa — cố đô của An Dương Vương xưa — thiết lập triều đình riêng, mở ra thời kỳ độc lập tự chủ cho dân tộc sau hơn 1000 năm chịu ách đô hộ. Triều Ngô tuy chỉ kéo dài 26 năm, nhưng ý nghĩa lịch sử của nó to lớn vô cùng: lần đầu tiên sau nghìn năm, người Việt có một vương triều của chính mình, đặt nền móng cho các triều đại huy hoàng tiếp theo.",
    events: [
      "Ngô Quyền dẫn quân từ Ái Châu ra Bắc đối đầu quân Nam Hán do Hoằng Tháo chỉ huy",
      "Bố trí trận địa cọc trên sông Bạch Đằng — chiến thuật quân sự thiên tài lợi dụng thủy triều",
      "Đại phá quân Nam Hán năm 938, Hoằng Tháo tử trận, kết thúc hơn nghìn năm Bắc thuộc",
      "Ngô Quyền xưng vương, đóng đô Cổ Loa, thiết lập vương triều độc lập đầu tiên",
      "Sau khi Ngô Quyền mất (944), đất nước rơi vào loạn 12 sứ quân kéo dài gần 20 năm",
    ],
  },
  {
    id: "dinh", period: "968 – 980", title: "Nhà Đinh – Đại Cồ Việt", short: "Đinh",
    person: "Đinh Tiên Hoàng", role: "người dẹp loạn 12 sứ quân",
    place: "Hoa Lư, Ninh Bình",
    mark: "Đặt quốc hiệu Đại Cồ Việt, xây kinh đô Hoa Lư",
    file: "Tuongdaidinhtienhoangde2.JPG",
    source: "https://commons.wikimedia.org/wiki/File:Tuongdaidinhtienhoangde2.JPG",
    seal: "丁", drop: "Đ", capital: "Hoa Lư", figure: "Đinh Tiên Hoàng",
    milestone: "Dẹp loạn 12 sứ quân",
    quote: "Một gậy làm nên núi, một lời xoay chuyển trời.",
    quoteAuthor: "Ca tụng Đinh Bộ Lĩnh",
    imageCaption: "Tượng Đinh Tiên Hoàng tại Hoa Lư, Ninh Bình",
    theme: "thống nhất",
    summary: "Đinh Bộ Lĩnh dẹp loạn 12 sứ quân, thống nhất đất nước, xưng hoàng đế đầu tiên trong lịch sử Việt Nam, lập quốc hiệu Đại Cồ Việt, đặt nền móng cho chế độ phong kiến tập quyền.",
    detail: "Sau cái chết của Ngô Quyền, đất nước rơi vào loạn 12 sứ quân kéo dài gần hai thập kỷ. Mười hai thế lực cát cứ do các tướng lĩnh và hào trưởng địa phương cầm đầu đã chia cắt đất nước, gây ra chiến tranh liên miên. Giữa cảnh hỗn loạn đó, Đinh Bộ Lĩnh — con trai Đinh Công Trứ, Thứ sử Hoan Châu — nổi lên như một thủ lĩnh kiệt xuất. Từ nhỏ, ông đã nổi tiếng với tài tổ chức: cùng đám trẻ chăn trâu chơi trò 'tập trận', ông đóng vai tướng chỉ huy, được chúng bạn suy tôn. Lớn lên, ông về nương nhờ sứ quân Trần Lãm, rồi từng bước thu phục các sứ quân khác bằng cả vũ lực lẫn ngoại giao. Năm 968, sau khi bình định xong toàn bộ 12 sứ quân, Đinh Bộ Lĩnh lên ngôi hoàng đế, lấy hiệu Đinh Tiên Hoàng, đặt niên hiệu Thái Bình, định quốc hiệu là Đại Cồ Việt. Ông là người đầu tiên trong lịch sử Việt Nam xưng hoàng đế — một tước hiệu ngang hàng với hoàng đế Trung Hoa, thể hiện tinh thần độc lập và tự tôn dân tộc mạnh mẽ. Kinh đô Hoa Lư được chọn bởi địa thế hiểm trở với núi non bao bọc như một pháo đài tự nhiên. Đinh Tiên Hoàng còn cho đúc tiền đồng Thái Bình Hưng Bảo, xây dựng bộ máy triều đình với các chức văn võ rõ ràng, đặt ra hình phạt nghiêm khắc để răn đe kẻ phản loạn. Đây là bước ngoặt quyết định chuyển đất nước từ tình trạng phân tán cát cứ sang một nhà nước phong kiến trung ương tập quyền thống nhất.",
    events: [
      "Đinh Bộ Lĩnh tập hợp lực lượng, lần lượt đánh dẹp và thu phục các sứ quân",
      "Dẹp xong loạn 12 sứ quân, thống nhất đất nước năm 968",
      "Lên ngôi hoàng đế, lấy hiệu Đinh Tiên Hoàng, đặt niên hiệu Thái Bình",
      "Đặt quốc hiệu Đại Cồ Việt, chọn Hoa Lư làm kinh đô với địa hình hiểm trở",
      "Đúc tiền Thái Bình Hưng Bảo — đồng tiền kim loại đầu tiên của nhà nước độc lập",
      "Xây dựng bộ máy triều đình phong kiến tập quyền với các quan văn võ",
    ],
  },
  {
    id: "tien-le", period: "980 – 1009", title: "Nhà Tiền Lê – giữ nước", short: "Tiền Lê",
    person: "Lê Đại Hành", role: "vị vua phá Tống, bình Chiêm",
    place: "Hoa Lư, Ninh Bình",
    mark: "Kháng chiến chống Tống, bình Chiêm, củng cố Đại Cồ Việt",
    file: "Le Dai Hanh statue.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Le_Dai_Hanh_statue.jpg",
    seal: "黎", drop: "L", capital: "Hoa Lư", figure: "Lê Đại Hành",
    milestone: "Phá Tống, bình Chiêm",
    quote: "Giữ nước non từ thuở trứng nước, đánh giặc Tống buổi đầu.",
    quoteAuthor: "Sử ký",
    imageCaption: "Tượng Lê Đại Hành tại đền vua Lê, Ninh Bình",
    theme: "giữ nước",
    summary: "Lê Hoàn lên ngôi trong cơn nguy biến khi vua Đinh còn thơ ấu và quân Tống xâm lược. Với chiến thắng Bạch Đằng 981 và cuộc Nam chinh phá Chiêm Thành, ông đã bảo vệ vững chắc nền độc lập non trẻ của Đại Cồ Việt.",
    detail: "Năm 979, Đinh Tiên Hoàng và con trưởng Đinh Liễn bị sát hại trong một vụ ám sát nội cung. Con trai thứ là Đinh Toàn mới 6 tuổi được đưa lên ngôi. Nhân cơ hội triều đình rối loạn, nhà Tống chuẩn bị một đạo quân lớn do Hầu Nhân Bảo chỉ huy tiến xuống xâm lược. Trước tình thế nguy nan, Thái hậu Dương Vân Nga — một phụ nữ có tầm nhìn chính trị sắc sảo — đã cùng triều thần tôn Lê Hoàn, vị Thập đạo tướng quân đầy tài năng, lên làm vua, lập ra nhà Tiền Lê. Lê Đại Hành tự mình cầm quân ra trận, tổ chức cuộc kháng chiến toàn diện. Trên sông Bạch Đằng, ông lại dùng chiến thuật cọc ngầm năm xưa của Ngô Quyền để tiêu diệt thủy quân Tống. Đồng thời, trên bộ, các cánh quân của ông chặn đánh quyết liệt ở vùng Lạng Sơn, khiến đại quân Tống đại bại. Năm 981, quân Tống tháo chạy về nước. Chưa dừng lại ở đó, Lê Đại Hành tiếp tục mang quân Nam chinh, đánh bại Chiêm Thành, buộc vương quốc này phải triều cống và cắt đất phía Bắc cho Đại Cồ Việt. Ông còn là vị vua chăm lo phát triển kinh tế: tổ chức lễ Tịch điền (vua tự cày ruộng) vào đầu xuân để khuyến khích nông nghiệp, cho đào kênh ngòi phục vụ thủy lợi. Dưới thời Lê Đại Hành, Đại Cồ Việt không chỉ đứng vững trước họa xâm lăng mà còn mở rộng lãnh thổ, phát triển kinh tế — đặt nền móng vững chắc cho thời kỳ hoàng kim của nhà Lý sau này.",
    events: [
      "Đinh Tiên Hoàng và Đinh Liễn bị ám sát (979), triều đình Đại Cồ Việt lâm vào khủng hoảng",
      "Thái hậu Dương Vân Nga cùng triều thần tôn Lê Hoàn lên ngôi, lập nhà Tiền Lê",
      "Quân Tống do Hầu Nhân Bảo chỉ huy tiến xuống xâm lược, Lê Đại Hành tự mình cầm quân chống giặc",
      "Chiến thắng Bạch Đằng 981: dùng cọc ngầm đánh tan thủy quân Tống, Hầu Nhân Bảo tử trận",
      "Nam chinh đánh bại Chiêm Thành, mở rộng lãnh thổ về phía Nam",
      "Tổ chức lễ Tịch điền đầu xuân — vua tự cày ruộng khuyến khích nông nghiệp",
    ],
  },
  {
    id: "ly", period: "1009 – 1225", title: "Nhà Lý – Thăng Long rồng bay", short: "Lý",
    person: "Lý Thái Tổ", role: "người dời đô ra Thăng Long",
    place: "Thăng Long, Hà Nội",
    mark: "Chiếu dời đô 1010, Văn Miếu, chùa Một Cột, 216 năm thịnh trị",
    file: "Ly Thai To statue.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Ly_Thai_To_statue.jpg",
    seal: "李", drop: "L", capital: "Thăng Long", figure: "Lý Thái Tổ · Lý Thường Kiệt",
    milestone: "Dời đô Thăng Long",
    quote: "Nam quốc sơn hà Nam đế cư, tiệt nhiên định phận tại thiên thư.",
    quoteAuthor: "Lý Thường Kiệt",
    imageCaption: "Chùa Một Cột giữa hồ sen — kinh đô Thăng Long",
    theme: "văn hiến",
    summary: "Lý Công Uẩn dời đô từ Hoa Lư ra Thăng Long năm 1010, mở ra kỷ nguyên văn minh rực rỡ bậc nhất lịch sử Đại Việt với Văn Miếu, Quốc Tử Giám, Phật giáo hưng thịnh và bản tuyên ngôn độc lập đầu tiên.",
    detail: "Năm 1009, Lê Long Đĩnh — vị vua cuối cùng của nhà Tiền Lê nổi tiếng tàn bạo — qua đời. Triều đình suy tôn Lý Công Uẩn, vị quan văn võ song toàn, lên ngôi, lập ra nhà Lý. Ngay năm 1010, ông ban Chiếu dời đô, một văn kiện lịch sử bất hủ, chuyển kinh đô từ Hoa Lư chật hẹp ra thành Đại La bên sông Hồng rộng lớn. Tương truyền khi thuyền ngự đến nơi, có rồng vàng bay lên, nên Lý Thái Tổ đặt tên kinh đô mới là Thăng Long (Rồng bay). Đây là một quyết định chiến lược vĩ đại: từ thế phòng thủ trong thung lũng núi đá, đất nước bước ra đồng bằng phì nhiêu, thuận lợi giao thương và phát triển. Thời Lý là đỉnh cao của Phật giáo Việt Nam với hàng loạt công trình kiến trúc tuyệt mỹ: chùa Diên Hựu (Một Cột), chùa Quỳnh Lâm, chùa Phật Tích, tháp Báo Thiên. Năm 1070, Lý Thánh Tông cho xây Văn Miếu thờ Khổng Tử và Chu Công. Năm 1076, Lý Nhân Tông mở Quốc Tử Giám — trường đại học đầu tiên của Đại Việt — đào tạo nhân tài cho đất nước. Về quân sự, năm 1075, Lý Thường Kiệt chủ động tiến công sang đất Tống, phá tan các căn cứ tập kết quân địch. Khi quân Tống phản công năm 1077, ông lập phòng tuyến sông Như Nguyệt (sông Cầu), và trong đêm tối cho người đọc vang bài thơ \"Nam quốc sơn hà\" từ đền thờ thần sông — bản tuyên ngôn độc lập đầu tiên của dân tộc. Nhà Lý tồn tại 216 năm với 9 đời vua, để lại di sản văn hóa đồ sộ và là một trong những triều đại vàng son nhất của Đại Việt.",
    events: [
      "Lý Công Uẩn lên ngôi (1009), lập nhà Lý, chấm dứt thời kỳ nhà Tiền Lê",
      "Chiếu dời đô năm 1010: dời kinh đô từ Hoa Lư ra thành Đại La, đặt tên Thăng Long",
      "Xây dựng Văn Miếu (1070) thờ Khổng Tử, mở Quốc Tử Giám (1076) — trường đại học đầu tiên",
      "Phật giáo phát triển cực thịnh: chùa Một Cột, chùa Quỳnh Lâm, tháp Báo Thiên, chùa Phật Tích",
      "Lý Thường Kiệt chủ động đánh Tống (1075), lập phòng tuyến Như Nguyệt (1077)",
      "Bài thơ Nam quốc sơn hà — bản tuyên ngôn độc lập đầu tiên của dân tộc Việt Nam",
    ],
  },
  {
    id: "tran", period: "1225 – 1400", title: "Nhà Trần – hào khí Đông A", short: "Trần",
    person: "Trần Hưng Đạo", role: "thống soái kháng Nguyên – Mông",
    place: "Nam Định / Bạch Đằng / Thăng Long",
    mark: "Ba lần kháng chiến chống Nguyên Mông, hội nghị Diên Hồng, Hịch tướng sĩ",
    file: "Tran Hung Dao statue.JPG",
    source: "https://commons.wikimedia.org/wiki/File:Tran_Hung_Dao_statue.JPG",
    seal: "陳", drop: "N", capital: "Thăng Long", figure: "Trần Hưng Đạo · Trần Nhân Tông",
    milestone: "Ba lần thắng Nguyên Mông",
    quote: "Đánh! — hai vạn bô lão điện Diên Hồng đồng thanh.",
    quoteAuthor: "Sử ký",
    imageCaption: "Chân dung Hưng Đạo Vương Trần Quốc Tuấn — danh tướng nhà Trần",
    theme: "hào khí",
    summary: "Nhà Trần với hào khí Đông A lừng lẫy đã ba lần đánh tan quân Nguyên Mông — đế chế hùng mạnh nhất thế giới thế kỷ XIII. Hội nghị Diên Hồng, Hịch tướng sĩ và chiến thắng Bạch Đằng 1288 là những trang sử chói lọi nhất của dân tộc.",
    detail: "Năm 1225, thông qua cuộc hôn nhân giữa Trần Cảnh và nữ hoàng nhí Lý Chiêu Hoàng do Trần Thủ Độ sắp đặt, nhà Trần thay thế nhà Lý trong hòa bình. Thời Trần nổi tiếng với ba lần kháng chiến chống quân Nguyên Mông — đế chế hùng mạnh nhất đương thời đã chinh phục gần như toàn bộ lục địa Á-Âu. Năm 1258, quân Nguyên Mông tiến vào Đại Việt lần đầu. Với chiến thuật \"thanh dã\" (vườn không nhà trống), quân Trần tạm rút lui chiến lược, rồi phản công thần tốc đánh tan quân giặc ở Đông Bộ Đầu. Năm 1285, 50 vạn quân Nguyên do Thoát Hoan chỉ huy xâm lược lần thứ hai. Trước thế giặc mạnh, Hưng Đạo Vương Trần Quốc Tuấn viết Hịch tướng sĩ — áng văn lừng lẫy khích lệ toàn quân. Hội nghị Diên Hồng với hai vạn bô lão đồng thanh hô \"Đánh!\" thể hiện ý chí toàn dân. Quân Trần phản công, đại thắng ở Hàm Tử, Chương Dương, giải phóng Thăng Long. Năm 1288, quân Nguyên xâm lược lần ba. Trần Hưng Đạo lại dùng trận địa cọc trên sông Bạch Đằng — nơi ba thế kỷ trước Ngô Quyền đã làm nên lịch sử — nhấn chìm toàn bộ đoàn thuyền chiến Nguyên Mông, bắt sống tướng Ô Mã Nhi. Ngoài võ công hiển hách, nhà Trần còn là triều đại lừng lẫy về văn hóa: Trần Nhân Tông sau khi nhường ngôi đã lên núi Yên Tử sáng lập Thiền phái Trúc Lâm — dòng thiền mang bản sắc Việt, và chữ Nôm được các vua Trần, thiền sư chú trọng phát triển.",
    events: [
      "Trần Cảnh lên ngôi (1225) qua cuộc hôn nhân với Lý Chiêu Hoàng, lập ra nhà Trần",
      "Kháng chiến lần 1 (1258): chiến thuật 'thanh dã', phản công đánh tan quân Nguyên ở Đông Bộ Đầu",
      "Hội nghị Diên Hồng — hai vạn bô lão toàn quốc đồng thanh hô 'Đánh!'",
      "Trần Hưng Đạo soạn Hịch tướng sĩ, khích lệ tinh thần toàn quân chống giặc",
      "Kháng chiến lần 2 (1285): đại thắng Hàm Tử, Chương Dương, giải phóng Thăng Long",
      "Kháng chiến lần 3 (1288): trận Bạch Đằng với cọc gỗ, bắt sống Ô Mã Nhi, tiêu diệt thủy quân Nguyên",
      "Trần Nhân Tông sáng lập Thiền phái Trúc Lâm Yên Tử — dòng thiền mang bản sắc Việt",
      "Phát triển chữ Nôm, văn hóa Đại Việt đạt đỉnh cao mới",
    ],
  },
  {
    id: "ho", period: "1400 – 1407", title: "Nhà Hồ – cải cách & Thành Tây Đô", short: "Hồ",
    person: "Hồ Quý Ly", role: "nhà cải cách quyết liệt",
    place: "Thành nhà Hồ, Thanh Hóa",
    mark: "Đổi quốc hiệu Đại Ngu, cải cách toàn diện, xây thành Tây Đô",
    file: "Cổng Nam.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Cổng_Nam.jpg",
    seal: "胡", drop: "H", capital: "Tây Đô (Thanh Hóa)", figure: "Hồ Quý Ly",
    milestone: "Cải cách & thất thủ",
    quote: "Chính sự phiền hà, để trong nước lòng dân oán hận.",
    quoteAuthor: "Đại Việt sử ký toàn thư",
    imageCaption: "Cổng đá Thành Nhà Hồ — Tây Đô Thanh Hóa",
    theme: "cải cách",
    summary: "Hồ Quý Ly soán ngôi nhà Trần, tiến hành cải cách toàn diện táo bạo — phát hành tiền giấy đầu tiên, hạn chế ruộng đất, cải cách giáo dục — và xây dựng thành Tây Đô bằng đá, di sản thế giới UNESCO. Dù chỉ tồn tại 7 năm, nhà Hồ mang tầm nhìn vượt thời đại.",
    detail: "Năm 1400, Hồ Quý Ly — một đại thần đầy quyền lực dưới triều Trần — truất ngôi vua Trần Thiếu Đế, lập ra nhà Hồ, đổi quốc hiệu là Đại Ngu. Ông là một trong những nhà cải cách táo bạo và có tầm nhìn nhất trong lịch sử phong kiến Việt Nam. Về kinh tế, ông phát hành tiền giấy Thông Bảo Hội Sao — lần đầu tiên người Việt dùng tiền giấy — dù gặp nhiều khó khăn trong lưu thông. Về ruộng đất, ông ban hành phép hạn điền: giới hạn số ruộng tư của các đại địa chủ, sung công phần vượt hạn vào tài sản nhà nước — một chính sách mang tính cách mạng đương thời. Về giáo dục, Hồ Quý Ly đưa toán học vào nội dung thi cử, tổ chức thi Hương và thi Hội quy củ hơn. Ông còn xây dựng thành Tây Đô (Thanh Hóa) — tòa thành bằng đá đồ sộ với những phiến đá xanh khổng lồ nặng tới 20 tấn, là kỳ quan kiến trúc quân sự được UNESCO công nhận là Di sản văn hóa thế giới. Tuy nhiên, những cải cách quá nhanh và mạnh của ông vấp phải sự chống đối từ tầng lớp quý tộc cũ. Năm 1406, nhà Minh vin cớ \"phù Trần diệt Hồ\" đưa 20 vạn quân sang xâm lược. Cuộc kháng chiến thất bại, cha con Hồ Quý Ly bị bắt đưa về Trung Quốc năm 1407. Dù gây nhiều tranh cãi, Hồ Quý Ly là một nhân vật lịch sử phức tạp — một nhà cải cách có tư tưởng vượt trước thời đại, nhưng lại mắc sai lầm trong việc tập hợp lòng dân.",
    events: [
      "Hồ Quý Ly truất ngôi Trần Thiếu Đế, lập nhà Hồ, đổi quốc hiệu Đại Ngu (1400)",
      "Phát hành tiền giấy Thông Bảo Hội Sao — tiền giấy đầu tiên trong lịch sử Việt Nam",
      "Ban hành phép hạn điền: giới hạn ruộng tư, tái phân phối đất đai — chính sách mang tính cách mạng",
      "Cải cách thi cử: đưa toán học, khoa học tự nhiên vào nội dung thi",
      "Xây dựng thành Tây Đô bằng đá — công trình đồ sộ, UNESCO công nhận di sản thế giới",
      "Quân Minh xâm lược (1406), cuộc kháng chiến thất bại, cha con Hồ Quý Ly bị bắt (1407)",
    ],
  },
  {
    id: "lam-son", period: "1407 – 1427", title: "Thuộc Minh & Lam Sơn", short: "Lam Sơn",
    person: "Lê Lợi", role: "lãnh tụ khởi nghĩa Lam Sơn",
    place: "Lam Sơn, Thanh Hóa",
    mark: "Mười năm khởi nghĩa, Bình Ngô đại cáo của Nguyễn Trãi",
    file: "Le Loi statue.JPG",
    source: "https://commons.wikimedia.org/wiki/File:Le_Loi_statue.JPG",
    seal: "黎", drop: "S", capital: "Đông Quan (Hà Nội)", figure: "Lê Lợi · Nguyễn Trãi",
    milestone: "Khởi nghĩa Lam Sơn",
    quote: "Đánh một trận sạch không kình ngạc, đánh hai trận tan tác chim muông.",
    quoteAuthor: "Nguyễn Trãi — Bình Ngô đại cáo",
    imageCaption: "Tượng đài Lê Lợi — lãnh tụ khởi nghĩa Lam Sơn chống quân Minh",
    theme: "phục quốc",
    summary: "Sau khi nhà Hồ sụp đổ và quân Minh đô hộ tàn bạo, Lê Lợi phất cờ khởi nghĩa Lam Sơn năm 1418. Mười năm nếm mật nằm gai, cùng Nguyễn Trãi làm nên chiến thắng vĩ đại, giành lại độc lập dân tộc với áng Bình Ngô đại cáo bất hủ.",
    detail: "Năm 1407, quân Minh xâm lược và nhanh chóng đè bẹp nhà Hồ, đặt nền đô hộ hà khắc lên Đại Việt, đổi tên thành quận Giao Chỉ. Hai mươi vạn quân Minh thực hiện chính sách đồng hóa triệt để: đốt sách, phá chùa, áp đặt văn hóa Hán. Năm 1418, Lê Lợi — một hào trưởng giàu lòng yêu nước ở vùng Lam Sơn (Thanh Hóa) — phất cờ khởi nghĩa, xưng Bình Định Vương. Những năm đầu vô cùng gian khổ: nghĩa quân ít người, thiếu lương, phải rút lên núi Chí Linh trốn tránh. Có lúc phải giết cả voi chiến và ngựa chiến để nuôi quân. Lê Lợi hỏi Nguyễn Trãi về kế sách, Nguyễn Trãi khuyên: \"Đánh vào lòng người là thượng sách, công thành là hạ sách\". Nhờ chiến lược đúng đắn — vừa đánh vừa đàm, kết hợp quân sự với ngoại giao — nghĩa quân dần lớn mạnh. Năm 1424, họ tiến vào Nghệ An, giải phóng cả một vùng rộng lớn làm bàn đạp. Năm 1427, đại quân Lam Sơn bao vây thành Đông Quan (Hà Nội), tiêu diệt hoàn toàn đạo quân cứu viện do Liễu Thăng chỉ huy trong trận Chi Lăng – Xương Giang. Quân Minh buộc phải đầu hàng và rút về nước. Sau chiến thắng, Nguyễn Trãi viết Bình Ngô đại cáo — áng thiên cổ hùng văn không chỉ tuyên bố độc lập mà còn khẳng định một chân lý muôn đời: \"Việc nhân nghĩa cốt ở yên dân, quân điếu phạt trước lo trừ bạo\". Cuộc khởi nghĩa Lam Sơn là một trong những cuộc chiến tranh giải phóng vĩ đại nhất trong lịch sử dân tộc Việt Nam.",
    events: [
      "Quân Minh đô hộ Đại Việt, đổi thành quận Giao Chỉ với chính sách đồng hóa tàn bạo (1407)",
      "Lê Lợi phất cờ khởi nghĩa ở Lam Sơn, xưng Bình Định Vương (1418)",
      "Những năm đầu gian khổ: rút lên núi Chí Linh, thiếu lương phải giết voi ngựa nuôi quân",
      "Nguyễn Trãi tìm đến Lam Sơn, dâng kế sách đánh vào lòng người, kết hợp quân sự và ngoại giao",
      "Tiến vào Nghệ An giải phóng miền Trung (1424), mở rộng địa bàn kháng chiến",
      "Chiến thắng Chi Lăng – Xương Giang (1427), tiêu diệt đạo quân cứu viện của Liễu Thăng",
      "Quân Minh đầu hàng, rút về nước, Nguyễn Trãi viết Bình Ngô đại cáo tuyên bố độc lập",
    ],
  },
  {
    id: "hau-le", period: "1428 – 1527", title: "Hậu Lê sơ – luật pháp & văn trị", short: "Hậu Lê",
    person: "Lê Thánh Tông", role: "vị vua anh minh nhất sử Việt",
    place: "Đông Kinh / Thăng Long",
    mark: "Bộ luật Hồng Đức, mở rộng bờ cõi, Nho học cực thịnh",
    file: "Statue of Lê Lợi.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Statue_of_Lê_Lợi.jpg",
    seal: "黎", drop: "T", capital: "Đông Kinh (Thăng Long)", figure: "Lê Thái Tổ · Lê Thánh Tông",
    milestone: "Luật Hồng Đức",
    quote: "Việc nhân nghĩa cốt ở yên dân, quân điếu phạt trước lo trừ bạo.",
    quoteAuthor: "Nguyễn Trãi — Bình Ngô đại cáo",
    imageCaption: "Văn Miếu Quốc Tử Giám — trường đại học đầu tiên của Đại Việt",
    theme: "văn trị",
    summary: "Thời Lê Thánh Tông là đỉnh cao của chế độ phong kiến Việt Nam với bộ luật Hồng Đức tiến bộ hàng đầu Đông Nam Á, nền hành chính hoàn thiện, bờ cõi mở rộng và Nho học phát triển cực thịnh.",
    detail: "Sau chiến thắng, Lê Lợi lên ngôi hoàng đế năm 1428, lập ra nhà Hậu Lê. Nhưng thời kỳ rực rỡ nhất là dưới triều Lê Thánh Tông (1460–1497) — vị vua được đánh giá là anh minh bậc nhất trong lịch sử phong kiến Việt Nam. Lên ngôi ở tuổi 18, ông đã mở ra kỷ nguyên thịnh trị chưa từng có. Công trình vĩ đại nhất của ông là bộ Quốc triều hình luật — còn gọi là Luật Hồng Đức — gồm 722 điều, được coi là bộ luật tiến bộ nhất Đông Nam Á đương thời. Điều đáng kinh ngạc: luật có nhiều điều khoản bảo vệ quyền lợi phụ nữ như quyền thừa kế tài sản, quyền ly hôn và quyền nuôi con — những quyền mà phương Tây phải hàng thế kỷ sau mới có. Về hành chính, ông cải tổ toàn diện: chia cả nước thành 13 đạo thừa tuyên, đứng đầu là Đô ty, Thừa ty và Hiến ty — hệ thống tam quyền phân lập kiểm soát lẫn nhau. Ông cho vẽ bản đồ Hồng Đức — tập bản đồ đầu tiên của quốc gia Đại Việt, ghi lại toàn bộ lãnh thổ từ ải Nam Quan tới đèo Cù Mông. Về quân sự, ông thân chinh Nam chinh, đánh bại Chiêm Thành, sáp nhập vùng đất phía Nam vào bản đồ Đại Việt. Văn hóa thời Hồng Đức cũng rực rỡ: ông sáng lập Hội Tao Đàn gồm 28 thi nhân tài hoa nhất, tự xưng Tao Đàn Nguyên Súy. Khoa cử được tổ chức định kỳ 3 năm, đào tạo ra tầng lớp nho sĩ tài năng. Thời Lê Thánh Tông thực sự là \"hoàng kim thời đại\" của phong kiến Việt Nam.",
    events: [
      "Lê Lợi lên ngôi (1428), lập nhà Hậu Lê, đặt niên hiệu Thuận Thiên",
      "Ban hành Bộ luật Hồng Đức với 722 điều — bộ luật tiến bộ nhất Đông Nam Á",
      "Cải cách hành chính: chia nước thành 13 đạo thừa tuyên, lập hệ thống tam ty kiểm soát lẫn nhau",
      "Vẽ bản đồ Hồng Đức — tập bản đồ quốc gia đầu tiên của Đại Việt",
      "Thân chinh Nam chinh đánh bại Chiêm Thành, mở rộng lãnh thổ về phía Nam",
      "Sáng lập Hội Tao Đàn, quy tụ 28 danh sĩ, phát triển văn thơ Nôm",
      "Khoa cử tổ chức quy củ 3 năm một lần, đào tạo nhân tài trên toàn quốc",
    ],
  },
  {
    id: "mac", period: "1527 – 1592", title: "Nhà Mạc – chuyển giao", short: "Mạc",
    person: "Mạc Đăng Dung", role: "người mở triều Mạc ở Thăng Long",
    place: "Đông Kinh / Cao Bằng",
    mark: "Lên thay Hậu Lê, đối đầu Nam triều Lê – Trịnh",
    file: "Statue of Emperor Mạc Thái Tông.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Statue_of_Emperor_Mạc_Thái_Tông.jpg",
    seal: "莫", drop: "N", capital: "Đông Kinh / Cao Bằng", figure: "Mạc Đăng Dung",
    milestone: "Lên thay Hậu Lê",
    quote: "Phát triển kinh tế, thủ công nghiệp và ngoại thương với phương Tây.",
    quoteAuthor: "Sử ký",
    imageCaption: "Thành Thăng Long thời Nam Bắc triều",
    theme: "chính thống",
    summary: "Nhà Mạc mở ra thời kỳ Nam Bắc triều phân tranh. Dù bị chính sử coi là 'ngụy triều', nhà Mạc có những đóng góp đáng kể về kinh tế với chính sách khuyến khích thủ công nghiệp và ngoại thương — lần đầu tiên mở cửa giao thương rộng rãi với các thương nhân phương Tây.",
    detail: "Năm 1527, Mạc Đăng Dung — một võ tướng xuất sắc từ thời Lê Sơ, từng trấn giữ Hải Dương — ép vua Lê Cung Hoàng nhường ngôi, lập ra nhà Mạc, đóng đô tại Thăng Long. Hành động này đã gây ra cuộc chiến tranh Nam Bắc triều ác liệt với lực lượng trung hưng nhà Lê do Nguyễn Kim lãnh đạo ở phía Nam. Sử sách thời Lê Trung Hưng gọi Mạc là \"ngụy triều\", nhưng nhìn nhận khách quan, nhà Mạc có những đóng góp đáng kể. Về kinh tế, các vua Mạc khuyến khích thương nghiệp và thủ công nghiệp phát triển mạnh mẽ. Đặc biệt, nhà Mạc là triều đại đầu tiên chủ động mở cửa giao thương với thương nhân phương Tây — người Bồ Đào Nha, Hà Lan, Anh — tại các thương cảng như Vân Đồn, Phố Hiến. Nhiều mặt hàng như tơ lụa, gốm sứ, nông sản được xuất khẩu. Chợ búa mọc lên khắp nơi, tạo nên một nền kinh tế hàng hóa sôi động. Về quân sự, nhà Mạc có lực lượng thủy quân mạnh và biết tận dụng ưu thế địa hình đồng bằng sông Hồng. Năm 1592, sau hơn 60 năm chiến tranh, Thăng Long thất thủ về tay quân Lê – Trịnh. Nhà Mạc rút lên Cao Bằng và tồn tại thêm gần 100 năm nữa trước khi bị tiêu diệt hoàn toàn vào năm 1677. Dù chỉ là một chương gây tranh cãi, thời kỳ nhà Mạc là giai đoạn bản lề quan trọng trong quá trình chuyển đổi kinh tế Việt Nam thời trung đại.",
    events: [
      "Mạc Đăng Dung ép Lê Cung Hoàng nhường ngôi, lập nhà Mạc tại Thăng Long (1527)",
      "Chiến tranh Nam – Bắc triều nổ ra với lực lượng Lê Trung Hưng do Nguyễn Kim lãnh đạo",
      "Mở cửa giao thương với thương nhân phương Tây: Bồ Đào Nha, Hà Lan, Anh",
      "Phát triển thủ công nghiệp và kinh tế hàng hóa tại các thương cảng",
      "Thất thủ Thăng Long (1592) trước quân Lê – Trịnh, rút lên Cao Bằng",
      "Nhà Mạc tồn tại ở Cao Bằng đến 1677 hoàn toàn bị tiêu diệt",
    ],
  },
  {
    id: "le-trung-hung", period: "1533 – 1789", title: "Lê Trung Hưng – Trịnh Nguyễn", short: "Lê Trung Hưng",
    person: "Nguyễn Hoàng", role: "người mở cơ nghiệp chúa Nguyễn Đàng Trong",
    place: "Đàng Ngoài / Đàng Trong / sông Gianh",
    mark: "Vua Lê – chúa Trịnh ở Bắc, chúa Nguyễn ở Nam, chia cắt kéo dài",
    file: "Nguyen hoang.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Nguyen_hoang.jpg",
    seal: "分", drop: "T", capital: "Thăng Long · Phú Xuân", figure: "Nguyễn Hoàng · Trịnh Kiểm",
    milestone: "Nam tiến mở cõi",
    quote: "Từ Đèo Ngang trở vào, đất ấy có thể dung thân muôn đời.",
    quoteAuthor: "Nguyễn Bỉnh Khiêm dặn Nguyễn Hoàng",
    imageCaption: "Bản đồ Đại Việt 1650 — thời kỳ Trịnh Nguyễn phân tranh",
    theme: "phân tranh",
    summary: "Thời kỳ vua Lê – chúa Trịnh cai trị Đàng Ngoài, chúa Nguyễn mở mang Đàng Trong. Đất nước bị chia cắt bởi sông Gianh dài 150 năm, nhưng cũng là thời kỳ của công cuộc Nam tiến vĩ đại, định hình lãnh thổ Việt Nam ngày nay.",
    detail: "Sau khi nhà Mạc cướp ngôi, Nguyễn Kim — một cựu thần triều Lê — tập hợp lực lượng trung hưng ở Thanh Hóa, đưa Lê Duy Ninh lên làm vua (Lê Trang Tông) năm 1533. Nhưng sau cái chết bí ẩn của Nguyễn Kim (1545), con rể ông là Trịnh Kiểm nắm trọn binh quyền. Kể từ đây, các vua Lê chỉ còn là bù nhìn — chúa Trịnh mới thực sự cai trị Đàng Ngoài với phủ Chúa ngay cạnh hoàng cung Thăng Long, tạo nên cục diện \"vua Lê chúa Trịnh\" độc đáo. Trong khi đó, Nguyễn Hoàng — con trai thứ của Nguyễn Kim — lo sợ bị Trịnh Kiểm sát hại, đã xin vào trấn thủ vùng Thuận Hóa xa xôi năm 1558. Tương truyền, trước khi đi, ông hỏi ý Trạng Trình Nguyễn Bỉnh Khiêm và được mách nước: \"Hoành Sơn nhất đái, vạn đại dung thân\" — Một dải Hoành Sơn (Đèo Ngang) có thể dung thân muôn đời. Từ đó, các chúa Nguyễn xây dựng cơ nghiệp ở Đàng Trong, biến Phú Xuân (Huế) thành trung tâm chính trị mới. Sông Gianh (Quảng Bình) trở thành ranh giới chia đôi đất nước suốt hơn 150 năm. Bảy lần Trịnh-Nguyễn đại chiến (1627–1672) không phân thắng bại, để lại biết bao đau thương. Dù phân tranh, cả hai bên đều có những thành tựu: chúa Trịnh phát triển văn hóa dân gian, chúa Nguyễn Nam tiến mạnh mẽ, sáp nhập vùng đất Champa và khai phá đồng bằng sông Cửu Long, đưa người Việt tới tận mũi Cà Mau. Thời kỳ này tuy đau thương vì chia cắt, nhưng chính công cuộc Nam tiến của các chúa Nguyễn đã định hình nên dải đất hình chữ S hùng vĩ của Việt Nam hôm nay.",
    events: [
      "Nguyễn Kim lập Lê Trang Tông, bắt đầu thời Lê Trung Hưng (1533)",
      "Trịnh Kiểm nắm quyền, mở đầu 200 năm 'vua Lê chúa Trịnh' ở Đàng Ngoài",
      "Nguyễn Hoàng xin vào trấn thủ Thuận Hóa (1558), được Nguyễn Bỉnh Khiêm mách kế 'dung thân muôn đời'",
      "Các chúa Nguyễn lập cơ nghiệp Đàng Trong, đóng đô ở Phú Xuân (Huế)",
      "Bảy lần chiến tranh Trịnh – Nguyễn (1627–1672), sông Gianh thành ranh giới chia cắt",
      "Chúa Nguyễn thực hiện Nam tiến, sáp nhập Champa và khai phá đồng bằng sông Cửu Long",
    ],
  },
  {
    id: "tay-son", period: "1778 – 1802", title: "Tây Sơn – Quang Trung", short: "Tây Sơn",
    person: "Quang Trung – Nguyễn Huệ", role: "anh hùng áo vải, hoàng đế",
    place: "Bình Định / Phú Xuân / Đống Đa",
    mark: "Lật đổ chúa Nguyễn, chúa Trịnh, vua Lê; đại phá quân Thanh 1789",
    file: "Quang Trung Nguyễn Huệ, Gò Đống Đa.JPG",
    source: "https://commons.wikimedia.org/wiki/File:Quang_Trung_Nguyễn_Huệ,_Gò_Đống_Đa.JPG",
    seal: "西", drop: "P", capital: "Phú Xuân", figure: "Quang Trung – Nguyễn Huệ",
    milestone: "Ngọc Hồi – Đống Đa 1789",
    quote: "Đánh cho sử tri Nam quốc anh hùng chi hữu chủ.",
    quoteAuthor: "Quang Trung",
    imageCaption: "Tượng đài Quang Trung Nguyễn Huệ — người anh hùng áo vải cờ đào",
    theme: "thần tốc",
    summary: "Phong trào nông dân Tây Sơn lật đổ cả ba tập đoàn phong kiến: chúa Nguyễn Đàng Trong, chúa Trịnh Đàng Ngoài và vua Lê. Nguyễn Huệ — Quang Trung — hành quân thần tốc ra Bắc, đại phá 29 vạn quân Thanh trong 5 ngày Tết Kỷ Dậu 1789, viết nên huyền thoại quân sự chói lọi.",
    detail: "Giữa thế kỷ XVIII, chế độ phong kiến Đàng Trong dưới thời chúa Nguyễn Phúc Thuần thối nát, quan lại hà hiếp dân nghèo. Từ ấp Tây Sơn (Bình Định), ba anh em Nguyễn Nhạc, Nguyễn Huệ, Nguyễn Lữ — con một gia đình nông dân khá giả nhưng có truyền thống võ nghệ — phất cờ khởi nghĩa năm 1771 với khẩu hiệu \"lấy của nhà giàu chia cho dân nghèo\". Trong vòng 15 năm, quân Tây Sơn làm nên điều kỳ diệu: lần lượt lật đổ chúa Nguyễn (1777), tiêu diệt quân Xiêm xâm lược trong trận Rạch Gầm – Xoài Mút (1785), lật đổ chúa Trịnh (1786), và cuối cùng là vua Lê. Nhưng đỉnh cao nhất là thiên tài quân sự Nguyễn Huệ. Khi 29 vạn quân Thanh tràn vào Thăng Long cuối năm 1788, Nguyễn Huệ lên ngôi hoàng đế lấy hiệu Quang Trung, rồi hành quân thần tốc từ Phú Xuân ra Bắc ngay trong dịp Tết Kỷ Dậu (1789). Chỉ trong 5 ngày (từ đêm 30 Tết đến sáng mùng 5), quân Tây Sơn đã đánh tan tác toàn bộ đại quân Thanh. Trận Ngọc Hồi – Đống Đa đi vào huyền thoại: tượng binh Tây Sơn xông thẳng vào doanh trại địch, quân Thanh hoảng loạn tháo chạy, tướng Tôn Sĩ Nghị bỏ chạy không kịp mang theo ấn tín. Sau chiến thắng, Quang Trung tiến hành cải cách toàn diện: đề cao chữ Nôm, mở khoa thi bằng chữ Nôm, cải cách giáo dục, khuyến khích sản xuất. Tiếc thay, ông đột ngột băng hà năm 1792 khi mới 40 tuổi. Không có Quang Trung, nhà Tây Sơn nhanh chóng suy yếu và bị Nguyễn Ánh — hậu duệ chúa Nguyễn — tiêu diệt năm 1802.",
    events: [
      "Ba anh em Nguyễn Nhạc, Nguyễn Huệ, Nguyễn Lữ khởi nghĩa ở Tây Sơn (1771)",
      "Lật đổ chúa Nguyễn ở Đàng Trong (1777) và chúa Trịnh ở Đàng Ngoài (1786)",
      "Chiến thắng Rạch Gầm – Xoài Mút (1785): đánh tan 5 vạn quân Xiêm trên sông Tiền",
      "Nguyễn Huệ lên ngôi hoàng đế Quang Trung, tiến quân ra Bắc (1788)",
      "Đại phá 29 vạn quân Thanh trong 5 ngày Tết Kỷ Dậu 1789: Ngọc Hồi – Đống Đa",
      "Quang Trung cải cách toàn diện: đề cao chữ Nôm, cải cách giáo dục và nông nghiệp",
      "Quang Trung đột ngột băng hà (1792), nhà Tây Sơn suy yếu, bị Nguyễn Ánh tiêu diệt (1802)",
    ],
  },
  {
    id: "nguyen", period: "1802 – 1945", title: "Nhà Nguyễn – kinh đô Huế", short: "Nguyễn",
    person: "Gia Long / Bảo Đại", role: "triều đại quân chủ cuối cùng",
    place: "Phú Xuân – Huế",
    mark: "Thống nhất lãnh thổ, xây Kinh thành Huế; kết thúc chế độ phong kiến 1945",
    file: "Emperor Gia Long.jpg",
    source: "https://commons.wikimedia.org/wiki/File:Emperor_Gia_Long.jpg",
    seal: "阮", drop: "T", capital: "Phú Xuân – Huế", figure: "Gia Long · Minh Mạng · Bảo Đại",
    milestone: "Thống nhất & kết thúc quân chủ",
    quote: "Trẫm muốn làm dân một nước tự do, hơn làm vua một nước bị trị.",
    quoteAuthor: "Bảo Đại, 1945",
    imageCaption: "Hoàng thành Huế — kinh đô cuối cùng của chế độ quân chủ Việt",
    theme: "di sản Huế",
    summary: "Triều Nguyễn thống nhất đất nước sau hàng thế kỷ phân tranh, xây dựng kinh đô Huế với quần thể di sản đồ sộ được UNESCO vinh danh. Đây là triều đại quân chủ cuối cùng, khép lại gần nghìn năm phong kiến Việt Nam khi Bảo Đại thoái vị tháng Tám 1945.",
    detail: "Năm 1802, sau 25 năm chiến tranh gian khổ, Nguyễn Ánh — hậu duệ của các chúa Nguyễn Đàng Trong — đánh bại hoàn toàn nhà Tây Sơn, lên ngôi hoàng đế lấy hiệu Gia Long, lập ra nhà Nguyễn. Đây là lần đầu tiên kể từ thời Lê Thánh Tông, đất nước được thống nhất hoàn toàn dưới một vương triều duy nhất. Gia Long chọn Phú Xuân (Huế) làm kinh đô, cho xây dựng Kinh thành Huế — quần thể kiến trúc đồ sộ gồm Hoàng thành, Tử Cấm thành và hệ thống lăng tẩm trải dài dọc sông Hương. Năm 1993, quần thể này được UNESCO công nhận là Di sản văn hóa thế giới. Dưới thời Minh Mạng (1820–1841), nhà Nguyễn đạt cực thịnh: lãnh thổ mở rộng tối đa, bộ máy hành chính hoàn chỉnh từ trung ương đến địa phương, văn hóa Nho giáo phát triển. Tuy nhiên, từ giữa thế kỷ XIX, Việt Nam phải đối mặt với làn sóng xâm lược của thực dân phương Tây. Năm 1858, liên quân Pháp – Tây Ban Nha nổ súng tấn công Đà Nẵng. Sau gần 30 năm kháng cự, triều Nguyễn lần lượt ký các hiệp ước bất bình đẳng: Nhâm Tuất (1862), Giáp Tuất (1874), Hác Măng và Patơnốt (1884), biến Việt Nam thành xứ bảo hộ của Pháp. Các vua Nguyễn từ đây chỉ còn là bù nhìn, thực quyền nằm trong tay chính quyền thực dân. Cuộc kháng chiến của nhân dân vẫn tiếp diễn dưới nhiều hình thức. Tháng Tám năm 1945, trước làn sóng cách mạng dâng cao, vua Bảo Đại — vị hoàng đế cuối cùng — tuyên bố thoái vị tại Ngọ Môn, Huế, trao ấn kiếm cho chính quyền cách mạng, chính thức chấm dứt gần một nghìn năm chế độ quân chủ Việt Nam. Nhà Nguyễn để lại những di sản đồ sộ: Quần thể di tích Huế, Nhã nhạc cung đình (kiệt tác di sản phi vật thể), Mộc bản triều Nguyễn và Châu bản triều Nguyễn — đều được UNESCO công nhận là di sản tư liệu thế giới.",
    events: [
      "Nguyễn Ánh đánh bại Tây Sơn, lên ngôi Gia Long, lập nhà Nguyễn (1802)",
      "Xây dựng Kinh thành Huế — quần thể kiến trúc đồ sộ, UNESCO công nhận di sản thế giới (1993)",
      "Minh Mạng cải cách hành chính, thống nhất lãnh thổ từ ải Nam Quan đến mũi Cà Mau",
      "Liên quân Pháp – Tây Ban Nha tấn công Đà Nẵng (1858), khởi đầu xâm lược Việt Nam",
      "Triều Nguyễn ký các hiệp ước bất bình đẳng, Việt Nam thành thuộc địa nửa phong kiến",
      "Bảo Đại — vị vua cuối cùng — thoái vị tại Ngọ Môn, Huế tháng 8/1945, chế độ quân chủ kết thúc",
      "Nhã nhạc cung đình Huế, Mộc bản và Châu bản triều Nguyễn — di sản tư liệu thế giới UNESCO",
    ],
  },
];

export { commonsUrl, fallbackImage, eras };
