export const env = {
    BUILD_MODE: import.meta.env.VITE_BUILD_MODE,
    WEBSITE_DOMAIN_DEVELOPMENT: import.meta.env.VITE_WEBSITE_DOMAIN_DEVELOPMENT,
    WEBSITE_DOMAIN_PRODUCTION: import.meta.env.VITE_WEBSITE_DOMAIN_PRODUCTION
}
